blender_exe: /home/anhnguyen/Downloads/blender-2.82-linux64/blender
blender_engine: BLENDER_EEVEE
output_dir: ./sample/output/
label_dict: ./annotation/OBJ_CLS.yaml
WIP_blend_file_path:

img_size: (640,480)

modes: 
  # - empty_space
  - empty_space_partial_earth
  
background:
  assets:
    earth_blend:
      dir: ./asset/background/earth
      import_object: Earth
      import_blend:  ./asset/background/earth/planet_earth_v1.blend
      earth_texture: ./asset/background/earth/earth_texture
      cloud_texture: ./asset/background/earth/cloud_texture
      camera_orbiting_range: ()
      creation_mode: import

    ## Depreciated
    # sky_blend:
    #   dir: ./asset/background/
    #   import_blend:
    #   sky_texture: ./asset/background/sky/sky_texture
    #   creation_mode: create

light:
  specify_config: False
  type: SUN
  angle: 360
  strength: 1000
  location: (4,1,6)
  rotation: (0,0,0)
  radius: 1

camera:
  space_target_range:
    depth: (8, 100) #From the axis of the camera
    horizontal_dist: (2.5, 36)   #Horizontal distance from the axis of the camera
    vertical_dist: (1, 20)

space_targets:
  range_num_obj: (1,6) 

  cubesats:
    included: True
    1U: ./asset/space_targets/cubesats/cubesat_1U.blend
    2U: ./asset/space_targets/cubesats/cubesat_2U.blend
    3U: ./asset/space_targets/cubesats/cubesat_3U.blend
    4U: ./asset/space_targets/cubesats/cubesat_4U.blend
    6U: ./asset/space_targets/cubesats/cubesat_6U.blend
    12U: ./asset/space_targets/cubesats/cubesat_12U.blend 
    textures: ./asset/space_targets/cubesats/textures/one_side #Must be the directory to the one_side cubesat texture

  other_st:
    included: True
    dir: ./asset/space_targets/other_st
    textures: ./asset/space_targets/other_st/textures

  other:
    included: True
    dir: ./asset/space_targets/other
    textures: ./asset/space_targets/other/textures

operation_config:
  num_cycle: 1
  num_iter_per_cycle: 1
  num_view_per_iter: 1