blender_exe: /home/anhnguyen/Downloads/blender-3.2.1-linux-x64/blender

output_dir: ./sample/output/

light:

camera:

background:
  modes: 
    - empty_space
    - empty_space_partial_earth
    - full_earth
  earth_blend:
    dir: ./asset/background/earth
    earth_texture: ./asset/background/sky/earth_texture
    cloud_texture: ./asset/background/sky/cloud_texture
    creation_mode: import

  sky_blend:
    dir: ./asset/background/sky
    sky_texture: ./asset/background/sky/sky_texture
    creation_mode: create


space_targets:
  cubesats:
    1U: ./asset/space_targets/cubesats/cubesat_1U.blend
    2U: ./asset/space_targets/cubesats/cubesat_2U.blend
    3U: ./asset/space_targets/cubesats/cubesat_3U.blend
    4U: ./asset/space_targets/cubesats/cubesat_4U.blend
    6U: ./asset/space_targets/cubesats/cubesat_6U.blend
    12U: ./asset/space_targets/cubesats/cubesat_12U.blend 
    textures: ./asset/space_targets/cubesats/textures

  other_st:
    included: true
    dir: ./asset/space_targets/other_st
    textures: ./asset/space_targets/other_st/textures

  other:
    included: true
    dir: ./asset/space_targets/other
    textures: ./asset/space_targets/other/textures